package scaffold

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"path/filepath"
	"strings"
)

// ParsedDomain is what AddInfraPostgres (and future infra/entrypoints
// generators) reads back from a domain layer generated by `domain add`.
type ParsedDomain struct {
	Module     string
	EntityName string
	// Fields excludes the always-present ID/Status fields, same convention
	// as DomainOptions.Fields.
	Fields []Field
	// Methods is the subset of domainMethodOrder actually declared on the
	// domain's Repository interface.
	Methods []string
}

// ParseDomain reads internal/domains/{domain}/{module}/entity.go and
// repository.go (as generated by `domain add`) and extracts the entity's
// fields and the Repository interface's method set.
func ParseDomain(rootDir, domain, module string) (ParsedDomain, error) {
	dir := filepath.Join(rootDir, "internal", "domains", domain, module)

	fields, entityName, err := parseEntityFields(filepath.Join(dir, "entity.go"))
	if err != nil {
		return ParsedDomain{}, err
	}

	methods, err := parseRepositoryMethods(filepath.Join(dir, "repository.go"))
	if err != nil {
		return ParsedDomain{}, err
	}

	return ParsedDomain{
		Module:     module,
		EntityName: entityName,
		Fields:     fields,
		Methods:    methods,
	}, nil
}

func parseEntityFields(path string) ([]Field, string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, "", fmt.Errorf("read %s (run `codegen domain add` first): %w", path, err)
	}

	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}

		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			var fields []Field
			for _, f := range st.Fields.List {
				typ := exprString(fset, f.Type)
				for _, name := range f.Names {
					if name.Name == "ID" || name.Name == "Status" {
						continue
					}
					fields = append(fields, Field{Name: name.Name, Type: typ})
				}
			}

			return fields, ts.Name.Name, nil
		}
	}

	return nil, "", fmt.Errorf("%s: no struct type found", path)
}

func parseRepositoryMethods(path string) ([]string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("read %s (run `codegen domain add` first): %w", path, err)
	}

	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}

		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "Repository" {
				continue
			}

			it, ok := ts.Type.(*ast.InterfaceType)
			if !ok {
				continue
			}

			var found []string
			for _, m := range it.Methods.List {
				if len(m.Names) == 0 {
					continue // embedded interface — not used by generated repositories
				}
				key := strings.ToLower(m.Names[0].Name)
				if domainMethodSet[key] {
					found = append(found, key)
				}
			}

			return orderMethods(found), nil
		}
	}

	return nil, fmt.Errorf("%s: Repository interface not found", path)
}

func orderMethods(methods []string) []string {
	set := make(map[string]bool, len(methods))
	for _, m := range methods {
		set[m] = true
	}

	out := make([]string, 0, len(methods))
	for _, m := range domainMethodOrder {
		if set[m] {
			out = append(out, m)
		}
	}

	return out
}

func exprString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, fset, expr)
	return buf.String()
}
