package scaffold

import "path/filepath"

// EntrypointsRabbitOptions controls what AddEntrypointsRabbit generates.
type EntrypointsRabbitOptions struct {
	// RootDir is the project root. Defaults to "." when empty.
	RootDir string
	// Domain and Module identify the domain layer to read (generated by
	// `domain add`) and the consumer package to generate.
	Domain string
	Module string
	// Force overwrites files that already exist.
	Force bool
}

// AddEntrypointsRabbit generates a RabbitMQ consumer — {module}_consumer.go
// (Consumer.Consume, unmarshaling into a {Module}Message mirroring the
// entity fields) and consumer_registry.go (GetConsumers, wiring the queue
// config) — following the pattern of
// internal/entrypoints/consumers/rabbit/handbook/city/ in
// go-sdk-rest-template. Reads the entity fields from the domain layer
// generated by `domain add` via go/ast, same as the other entrypoints/infra
// generators.
func AddEntrypointsRabbit(opts EntrypointsRabbitOptions) (InfraResult, error) {
	root := opts.RootDir

	if root == "" {
		root = "."
	}

	if err := validateDomainModule(opts.Domain, opts.Module); err != nil {
		return InfraResult{}, err
	}

	parsed, err := ParseDomain(root, opts.Domain, opts.Module)

	if err != nil {
		return InfraResult{}, err
	}

	data := struct {
		Domain string
		Module string
		Fields []modelField
	}{
		Domain: opts.Domain,
		Module: parsed.Module,
		Fields: toModelFields(parsed.Fields),
	}

	consumerDir := filepath.Join("internal", "entrypoints", "consumers", "rabbit", opts.Domain, opts.Module)

	targets := []struct {
		relName string
		tmpl    string
	}{
		{parsed.Module + "_consumer.go", "templates/entrypoints/rabbit/consumer.go.tmpl"},
		{"consumer_registry.go", "templates/entrypoints/rabbit/consumer_registry.go.tmpl"},
	}

	result := InfraResult{Modules: []string{
		modulesBase + "gosdk-rabbit-core",
		"github.com/ThreeDotsLabs/watermill",
	}}

	for _, t := range targets {
		fr, err := generateFile(root, filepath.Join(consumerDir, t.relName), t.tmpl, data, opts.Force)

		if err != nil {
			return InfraResult{}, err
		}

		result.Files = append(result.Files, fr)
	}

	return result, nil
}
