package scaffold

import (
	"fmt"
	"path/filepath"

	"github.com/exgamer/go-sdk-generator/internal/gomod"
)

var entrypointKinds = map[string]bool{
	"admin":  true,
	"client": true,
}

// EntrypointsHttpOptions controls what AddEntrypointsHttp generates.
type EntrypointsHttpOptions struct {
	// RootDir is the project root. Defaults to "." when empty.
	RootDir string
	// Kind is who the entrypoint is for: "admin" or "client". It only
	// controls the output directory (internal/entrypoints/{kind}/http/...) —
	// go-sdk-rest-template has no "client" example to model a structural
	// difference on, so none is invented here.
	Kind string
	// Domain and Module identify the domain layer to read (generated by
	// `domain add`) and the entrypoints package to generate.
	Domain string
	Module string
	// Prefix is the route group prefix (router.Group(Prefix)). Defaults to
	// "/" + the last segment of the project's module path, matching
	// go-sdk-rest-template's own city routes (router.Group("/rest-template")).
	Prefix string
	// Force overwrites files that already exist.
	Force bool
}

// AddEntrypointsHttp generates the HTTP entrypoints layer — handler.go,
// routes.go, request.go, response.go, mapper.go — for a module whose domain
// layer was already generated by `domain add`, following the pattern of
// internal/entrypoints/admin/http/handbook/city/ in go-sdk-rest-template.
// Like infra, it reads the entity fields and the Repository method set from
// the generated domain code via go/ast — Index/View/Create/Update/Delete
// are generated for whichever of Paginated/GetById/Create/Update/Delete
// exist on the domain Repository (Activate/Deactivate have no HTTP mapping
// in the reference project, so they're not exposed here).
func AddEntrypointsHttp(opts EntrypointsHttpOptions) (InfraResult, error) {
	root := opts.RootDir

	if root == "" {
		root = "."
	}

	if !entrypointKinds[opts.Kind] {
		return InfraResult{}, fmt.Errorf("unknown entrypoint kind %q (allowed: admin, client)", opts.Kind)
	}

	if err := validateDomainModule(opts.Domain, opts.Module); err != nil {
		return InfraResult{}, err
	}

	parsed, err := ParseDomain(root, opts.Domain, opts.Module)

	if err != nil {
		return InfraResult{}, err
	}

	if len(parsed.Methods) == 0 {
		return InfraResult{}, fmt.Errorf("internal/domains/%s/%s/repository.go: Repository interface has no recognized methods", opts.Domain, opts.Module)
	}

	modulePath, err := gomod.ModulePath(root)

	if err != nil {
		return InfraResult{}, fmt.Errorf("determine module path (run `go mod init` first): %w", err)
	}

	prefix := opts.Prefix

	if prefix == "" {
		prefix = "/" + lastSegment(modulePath)
	}

	flags := buildMethodFlags(parsed.Methods)

	data := struct {
		Module       string
		EntityName   string
		TableName    string
		DomainImport string
		Prefix       string
		Fields       []modelField
		SearchFields []modelField
		methodFlags
	}{
		Module:       parsed.Module,
		EntityName:   parsed.EntityName,
		TableName:    pluralize(parsed.Module),
		DomainImport: modulePath + "/internal/domains/" + opts.Domain + "/" + opts.Module,
		Prefix:       prefix,
		Fields:       toModelFields(parsed.Fields),
		SearchFields: toModelFields(searchableFields(parsed.Fields)),
		methodFlags:  flags,
	}

	entrypointsDir := filepath.Join("internal", "entrypoints", opts.Kind, "http", opts.Domain, opts.Module)

	targets := []struct {
		relName string
		tmpl    string
	}{
		{"request.go", "templates/entrypoints/http/request.go.tmpl"},
		{"response.go", "templates/entrypoints/http/response.go.tmpl"},
		{"mapper.go", "templates/entrypoints/http/mapper.go.tmpl"},
		{"handler.go", "templates/entrypoints/http/handler.go.tmpl"},
		{"routes.go", "templates/entrypoints/http/routes.go.tmpl"},
	}

	result := InfraResult{Modules: []string{
		modulesBase + "gosdk-http-core",
		"github.com/gin-gonic/gin",
	}}
	if flags.HasPaginated {
		result.Modules = append(result.Modules, modulesBase+"gosdk-db-core")
	}

	for _, t := range targets {
		fr, err := generateFile(root, filepath.Join(entrypointsDir, t.relName), t.tmpl, data, opts.Force)

		if err != nil {
			return InfraResult{}, err
		}

		result.Files = append(result.Files, fr)
	}

	return result, nil
}
