package scaffold

import (
	"fmt"
	"path/filepath"

	"github.com/exgamer/go-sdk-generator/internal/gomod"
)

// InfraRedisOptions controls what AddInfraRedis generates.
type InfraRedisOptions struct {
	// RootDir is the project root. Defaults to "." when empty.
	RootDir string
	// Domain and Module identify the domain layer to read (generated by
	// `domain add`) and the infra package to generate.
	Domain string
	Module string
	// Force overwrites the file if it already exists.
	Force bool
}

// AddInfraRedis generates a Redis caching repository for a module whose
// domain layer was already generated by `domain add` — Set{Entity},
// Get{Entity}ById, Invalidate{Entity}Cache, following the pattern of
// internal/infrastructure/redis/handbook/city/repository.go in
// go-sdk-rest-template. Unlike the postgres repository, this one doesn't
// implement the domain Repository interface (it's a supplementary cache,
// same as in the reference project) so it's always the same 3 methods
// regardless of which methods `domain add` generated.
func AddInfraRedis(opts InfraRedisOptions) (InfraResult, error) {
	root := opts.RootDir

	if root == "" {
		root = "."
	}

	if err := validateDomainModule(opts.Domain, opts.Module); err != nil {
		return InfraResult{}, err
	}

	parsed, err := ParseDomain(root, opts.Domain, opts.Module)

	if err != nil {
		return InfraResult{}, err
	}

	modulePath, err := gomod.ModulePath(root)

	if err != nil {
		return InfraResult{}, fmt.Errorf("determine module path (run `go mod init` first): %w", err)
	}

	data := struct {
		Module       string
		EntityName   string
		DomainImport string
		KeyPrefix    string
	}{
		Module:       parsed.Module,
		EntityName:   parsed.EntityName,
		DomainImport: modulePath + "/internal/domains/" + opts.Domain + "/" + opts.Module,
		KeyPrefix:    opts.Domain + ":" + opts.Module + ":",
	}

	relPath := filepath.Join("internal", "infrastructure", "redis", opts.Domain, opts.Module, "repository.go")

	fr, err := generateFile(root, relPath, "templates/infra/redis/repository.go.tmpl", data, opts.Force)

	if err != nil {
		return InfraResult{}, err
	}

	return InfraResult{
		Files:   []FileResult{fr},
		Modules: []string{modulesBase + "gosdk-redis-core", "github.com/redis/go-redis/v9"},
	}, nil
}
