package scaffold

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/exgamer/go-sdk-generator/internal/gomod"
)

// InfraHttpOptions controls what AddInfraHttp generates.
type InfraHttpOptions struct {
	// RootDir is the project root. Defaults to "." when empty.
	RootDir string
	// Domain and Module identify the domain layer to read (generated by
	// `domain add`) and the infra package to generate.
	Domain string
	Module string
	// Force overwrites files that already exist.
	Force bool
}

// AddInfraHttp generates an HTTP-client repository for a module whose
// domain layer was already generated by `domain add` — model.go (response
// shape), mapper.go, repository.go (HttpRepository.GetById calling out to
// an external service), plus internal/configs/{module}_config.go holding
// the external service's host. Follows the pattern of
// internal/infrastructure/http/handbook/city/ in go-sdk-rest-template for
// the repository shape, and the config-injection pattern found in
// downstream services (e.g. parking-session-service's
// internal/infrastructure/http/fiscalization/webkassa +
// internal/configs/fiscal_config.go) for how the host is supplied: a
// mapstructure-tagged config struct, injected via the constructor, rather
// than a hardcoded/templated URL.
// Like the redis repository, it doesn't implement the domain Repository
// interface — it's a standalone cross-service client, wired up manually
// wherever it's needed.
func AddInfraHttp(opts InfraHttpOptions) (InfraResult, error) {
	root := opts.RootDir

	if root == "" {
		root = "."
	}

	if err := validateDomainModule(opts.Domain, opts.Module); err != nil {
		return InfraResult{}, err
	}

	parsed, err := ParseDomain(root, opts.Domain, opts.Module)

	if err != nil {
		return InfraResult{}, err
	}

	modulePath, err := gomod.ModulePath(root)

	if err != nil {
		return InfraResult{}, fmt.Errorf("determine module path (run `go mod init` first): %w", err)
	}

	data := struct {
		Domain        string
		Module        string
		EntityName    string
		TableName     string
		DomainImport  string
		ConfigsImport string
		EnvVar        string
		Fields        []Field
		ModelFields   []modelField
	}{
		Domain:        opts.Domain,
		Module:        parsed.Module,
		EntityName:    parsed.EntityName,
		TableName:     pluralize(parsed.Module),
		DomainImport:  modulePath + "/internal/domains/" + opts.Domain + "/" + opts.Module,
		ConfigsImport: modulePath + "/internal/configs",
		EnvVar:        strings.ToUpper(parsed.Module) + "_SERVICE_HOST",
		Fields:        parsed.Fields,
		ModelFields:   toModelFields(parsed.Fields),
	}

	infraDir := filepath.Join("internal", "infrastructure", "http", opts.Domain, opts.Module)

	targets := []struct {
		relPath string
		tmpl    string
	}{
		{filepath.Join(infraDir, "model.go"), "templates/infra/http/model.go.tmpl"},
		{filepath.Join(infraDir, "mapper.go"), "templates/infra/http/mapper.go.tmpl"},
		{filepath.Join(infraDir, "repository.go"), "templates/infra/http/repository.go.tmpl"},
		{filepath.Join("internal", "configs", opts.Module+"_config.go"), "templates/infra/http/config.go.tmpl"},
	}

	result := InfraResult{Modules: []string{
		modulesBase + "gosdk-http-core",
		modulesBase + "gosdk-http-request-builder",
	}}
	for _, t := range targets {
		fr, err := generateFile(root, t.relPath, t.tmpl, data, opts.Force)

		if err != nil {
			return InfraResult{}, err
		}

		result.Files = append(result.Files, fr)
	}

	return result, nil
}
