package scaffold

import (
	"fmt"
	"path/filepath"

	"git.mpinnovations.kz/mps/go-packages/gosdk-generator/internal/gomod"
)

// InfraHttpOptions controls what AddInfraHttp generates.
type InfraHttpOptions struct {
	// RootDir is the project root. Defaults to "." when empty.
	RootDir string
	// Domain and Module identify the domain layer to read (generated by
	// `domain add`) and the infra package to generate.
	Domain string
	Module string
	// Force overwrites files that already exist.
	Force bool
}

// AddInfraHttp generates an HTTP-client repository for a module whose
// domain layer was already generated by `domain add` — model.go (response
// shape), mapper.go, repository.go (HttpRepository.GetById calling out to
// an external service) — following the pattern of
// internal/infrastructure/http/handbook/city/ in go-sdk-rest-template.
// Like the redis repository, it doesn't implement the domain Repository
// interface — it's a standalone cross-service client, wired up manually
// wherever it's needed.
func AddInfraHttp(opts InfraHttpOptions) (InfraResult, error) {
	root := opts.RootDir
	if root == "" {
		root = "."
	}

	if !domainNameRe.MatchString(opts.Domain) {
		return InfraResult{}, fmt.Errorf("invalid domain %q: lowercase letters/digits only, starting with a letter", opts.Domain)
	}
	if !domainNameRe.MatchString(opts.Module) {
		return InfraResult{}, fmt.Errorf("invalid module %q: lowercase letters/digits only, starting with a letter", opts.Module)
	}

	parsed, err := ParseDomain(root, opts.Domain, opts.Module)
	if err != nil {
		return InfraResult{}, err
	}

	modulePath, err := gomod.ModulePath(root)
	if err != nil {
		return InfraResult{}, fmt.Errorf("determine module path (run `go mod init` first): %w", err)
	}

	data := struct {
		Module       string
		EntityName   string
		TableName    string
		DomainImport string
		Fields       []Field
		ModelFields  []modelField
	}{
		Module:       parsed.Module,
		EntityName:   parsed.EntityName,
		TableName:    pluralize(parsed.Module),
		DomainImport: modulePath + "/internal/domains/" + opts.Domain + "/" + opts.Module,
		Fields:       parsed.Fields,
		ModelFields:  toModelFields(parsed.Fields),
	}

	infraDir := filepath.Join("internal", "infrastructure", "http", opts.Domain, opts.Module)

	targets := []struct {
		relName string
		tmpl    string
	}{
		{"model.go", "templates/infra/http/model.go.tmpl"},
		{"mapper.go", "templates/infra/http/mapper.go.tmpl"},
		{"repository.go", "templates/infra/http/repository.go.tmpl"},
	}

	result := InfraResult{Modules: []string{
		modulesBase + "gosdk-http-core",
		modulesBase + "gosdk-http-request-builder",
	}}
	for _, t := range targets {
		fr, err := generateFile(root, filepath.Join(infraDir, t.relName), t.tmpl, data, opts.Force)
		if err != nil {
			return InfraResult{}, err
		}
		result.Files = append(result.Files, fr)
	}

	return result, nil
}
