package scaffold

import (
	"fmt"
	"path/filepath"

	"github.com/exgamer/go-sdk-generator/internal/gomod"
)

// InfraPostgresOptions controls what AddInfraPostgres generates.
type InfraPostgresOptions struct {
	// RootDir is the project root. Defaults to "." when empty.
	RootDir string
	// Domain and Module identify the domain layer to read (generated by
	// `domain add`) and the infra package to generate.
	Domain string
	Module string
	// Force overwrites files that already exist.
	Force bool
}

// modelField is a domain Field annotated with its GORM column name, for
// templates that need both.
type modelField struct {
	Name   string
	Type   string
	Column string
}

func toModelFields(fields []Field) []modelField {
	out := make([]modelField, 0, len(fields))

	for _, f := range fields {
		out = append(out, modelField{Name: f.Name, Type: f.Type, Column: toSnakeCase(f.Name)})
	}

	return out
}

// InfraResult is the outcome of AddInfraPostgres and the other
// infra/entrypoints/bootstrap generators that share the same shape.
type InfraResult struct {
	Files []FileResult
	// Modules are the module paths needed in go.mod for the generated code
	// (depends on which Repository methods were found on the domain).
	Modules []string
	// ModuleRegistered is set by AddBootstrap: whether app.go's
	// RegisterAndInitModules(...) call was updated (false if the module was
	// already registered). Unused by every other generator.
	ModuleRegistered bool
}

// AddInfraPostgres generates the postgres infrastructure layer — model.go,
// mapper.go, repository.go — for a module whose domain layer was already
// generated by `domain add`. It reads the entity fields and the set of
// Repository methods straight from the generated domain/entity.go and
// domain/repository.go (via go/ast), so fields/methods never need to be
// re-specified.
func AddInfraPostgres(opts InfraPostgresOptions) (InfraResult, error) {
	root := opts.RootDir

	if root == "" {
		root = "."
	}

	if err := validateDomainModule(opts.Domain, opts.Module); err != nil {
		return InfraResult{}, err
	}

	parsed, err := ParseDomain(root, opts.Domain, opts.Module)

	if err != nil {
		return InfraResult{}, err
	}

	if len(parsed.Methods) == 0 {
		return InfraResult{}, fmt.Errorf("internal/domains/%s/%s/repository.go: Repository interface has no recognized methods", opts.Domain, opts.Module)
	}

	modulePath, err := gomod.ModulePath(root)

	if err != nil {
		return InfraResult{}, fmt.Errorf("determine module path (run `go mod init` first): %w", err)
	}

	flags := buildMethodFlags(parsed.Methods)

	data := struct {
		Module       string
		EntityName   string
		TableName    string
		DomainImport string
		Fields       []Field
		ModelFields  []modelField
		SearchFields []modelField
		methodFlags
	}{
		Module:       parsed.Module,
		EntityName:   parsed.EntityName,
		TableName:    pluralize(parsed.Module),
		DomainImport: modulePath + "/internal/domains/" + opts.Domain + "/" + opts.Module,
		Fields:       parsed.Fields,
		ModelFields:  toModelFields(parsed.Fields),
		SearchFields: toModelFields(searchableFields(parsed.Fields)),
		methodFlags:  flags,
	}

	infraDir := filepath.Join("internal", "infrastructure", "postgres", opts.Domain, opts.Module)

	targets := []struct {
		relName string
		tmpl    string
	}{
		{"model.go", "templates/infra/postgres/model.go.tmpl"},
		{"mapper.go", "templates/infra/postgres/mapper.go.tmpl"},
		{"repository.go", "templates/infra/postgres/repository.go.tmpl"},
	}

	result := InfraResult{Modules: infraPostgresModules(flags)}

	for _, t := range targets {
		fr, err := generateFile(root, filepath.Join(infraDir, t.relName), t.tmpl, data, opts.Force)

		if err != nil {
			return InfraResult{}, err
		}

		result.Files = append(result.Files, fr)
	}

	return result, nil
}

// infraPostgresModules returns the module paths the generated infra code
// needs: gorm.io/gorm always, gosdk-db-core only when Paginated is present.
func infraPostgresModules(flags methodFlags) []string {
	modules := []string{"gorm.io/gorm"}

	if flags.HasPaginated {
		modules = append(modules, modulesBase+"gosdk-db-core")
	}

	return modules
}
